# scripts generated by open ai
import openai

openai.api_key = 'YOUR_API_KEY'

ssml_scripts = {
    "42": [
        """<speak>
    <prosody rate="105%">
        <break time="500ms"/>
        Welcome to <emphasis level="strong">TCS</emphasis>! In the next few moments, we’ll explore everything that makes TCS unique.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Founded in 1968 and headquartered in <emphasis>Mumbai</emphasis>, TCS employs over 200,000 professionals, excelling in IT services and consulting.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        TCS holds an overall rating of 3.7 from more than 80,000 reviews. Employees highly value job security, while promotions and appraisals are areas for growth.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Curious about salaries? TCS offers competitive pay, with roles like System Engineer, Business Analyst, and IT Analyst ranging from 4.8 to 15 lakh rupees annually.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        TCS employees enjoy valuable benefits, including health insurance, professional training, shuttle services, and free meals. These perks make work at TCS even more rewarding.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        In 2024, TCS earned recognition at the ABECA awards, being honored as a top-rated mega company and a leader in financial services.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Competing with industry giants like Wipro, Infosys, and Accenture, TCS stands strong in the IT landscape, driven by quality and commitment.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Thank you for discovering TCS with us. We appreciate your interest!
    </prosody>
</speak>
""",
    ],
    "41": [
        """<speak>
    <prosody rate="105%">
        Welcome to <emphasis level="strong">Infosys</emphasis>! In the next few moments, we’ll explore everything that makes Infosys a unique and exciting place to work.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Founded in 1981 and headquartered in <emphasis>Bengaluru</emphasis>, Infosys has grown to employ between 250,000 and 350,000 professionals in IT services and consulting.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Infosys holds a rating of <emphasis level="strong">3.9</emphasis> from over <emphasis level="strong">100,000 reviews</emphasis>. The company excels in work-life balance but has room for improvement in promotions and appraisals.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Interested in compensation? Infosys offers salaries ranging from 5.2 to 18 lakh rupees annually for roles like Software Engineer, Data Analyst, and Senior Consultant.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Infosys employees benefit from health insurance, work from home options, free meals, and professional training. These perks are highly appreciated by the workforce.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        In 2024, Infosys was recognized as a top-rated mega company in the ABECA awards, celebrating its excellence and leadership in the IT industry.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Competing with companies like TCS, Accenture, and Cognizant, Infosys continues to lead with its strong workforce and commitment to excellence in IT services.
    </prosody>
</speak>
""",
        """<speak>
    <prosody rate="105%">
        Thank you for exploring Infosys with us! We appreciate your interest in discovering more about our dynamic and innovative company.
    </prosody>
</speak>
""",
    ],
    "114": [
        """<speak>
        <prosody rate="105%">
            Welcome to <emphasis level="strong">Amazon</emphasis>! In the next few moments, we’ll explore everything that makes Amazon an exciting place to work.
        </prosody>
    </speak>""",
        """<speak>
        <prosody rate="105%">
            Founded in 1994 and headquartered in <emphasis>Seattle</emphasis>, Amazon is a global leader in E-Commerce, employing over 10,000 individuals in this fast-paced and innovative industry.
        </prosody>
    </speak>""",
        """<speak>
        <prosody rate="105%">
            Amazon holds an overall rating of <emphasis level="strong">4.0</emphasis> from more than <emphasis level="strong">50,000 reviews</emphasis>. Employees particularly appreciate our strong work culture, while work-life balance is an area to improve.
        </prosody>
    </speak>""",
        """<speak>
        <prosody rate="105%">
            Interested in salary expectations? At Amazon, roles like Software Development Engineer and Operations Manager offer competitive pay, with salaries ranging from $7,000 to $20,000 annually, depending on experience.
        </prosody>
    </speak>""",
        """<speak>
        <prosody rate="105%">
            Amazon employees enjoy fantastic benefits, including health insurance and stock options. Around 85% of our employees value these benefits, which make working here even more rewarding.
        </prosody>
    </speak>""",
        """<speak>
        <prosody rate="105%">
            In 2024, Amazon was honored at the ABECA awards as the top-rated E-Commerce company, showcasing our commitment to excellence and employee satisfaction.
        </prosody>
    </speak>""",
        """<speak>
        <prosody rate="105%">
            Competing with industry giants like <emphasis>Flipkart</emphasis>, <emphasis>Google</emphasis>, and <emphasis>Nvidia</emphasis>, Amazon continues to lead with strong ratings and a top position in the market.
        </prosody>
    </speak>""",
        """<speak>
        <prosody rate="105%">
            Thank you for discovering Amazon with us. We appreciate your interest in our journey and look forward to what the future holds!
        </prosody>
    </speak>""",
    ],
}
